using BaseConverter.Enums;
using BaseConverter.Management;

namespace BaseConverter.Models
{
    public class ClienteModel
    {
        public int IdCadCli { get; set; } = 1;
        public int IdCadFilial { get; set; } = 1;
        public int? IdCadFun { get; set; } = null;
        public int? IdCadRep { get; set; } = null;
        public string Nome { get; set; } = "SEM NOME";
        public string NomeFantasia { get; set; } = string.Empty;
        public string Bairro { get; set; } = string.Empty;
        public string BairroCob { get; set; } = string.Empty;
        public string Celular { get; set; } = string.Empty;
        public string Cep { get; set; } = string.Empty;
        public string CepCob { get; set; } = string.Empty;
        public string Cidade { get; set; } = "Divinópolis";
        public string CidadeCob { get; set; } = string.Empty;
        public string Complemento { get; set; } = string.Empty;
        public string ComplementoCob { get; set; } = string.Empty;
        public string Conjuge { get; set; } = string.Empty;
        public string Contato { get; set; } = string.Empty;
        public string CpfCnpj { get; set; } = string.Empty;
        public string TipoDocumento => CpfCnpj.Length == 11 ? "CPF" : CpfCnpj.Length == 14 ? "CNPJ" : string.Empty;
        public string CxPostal { get; set; } = string.Empty;
        public string CxPostalCob { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;
        public string Ende { get; set; } = string.Empty;
        public string EndeCob { get; set; } = string.Empty;
        public string EstadoCivil { get; set; } = string.Empty;
        public string Fax { get; set; } = string.Empty;
        public string FaxCob { get; set; } = string.Empty;
        public string InscEst { get; set; } = string.Empty;
        public string InscMun { get; set; } = string.Empty;
        public decimal LimiteDeCredito { get; set; } = 0.00m;
        public string Mae { get; set; } = string.Empty;
        public DateTime? Nascimento { get; set; } = null;
        public string Nacionalidade { get; set; } = string.Empty;
        public string Numero { get; set; } = string.Empty;
        public string NumeroCob { get; set; } = string.Empty;
        public string Obs { get; set; } = string.Empty;
        public string Pai { get; set; } = string.Empty;
        public string Rg { get; set; } = string.Empty;
        public string Sexo { get; set; } = string.Empty;
        public string Tel { get; set; } = string.Empty;
        public string TelCob { get; set; } = string.Empty;
        public bool UtilCob { get; set; } = false;
        public bool Bloqueado { get; set; } = false;
        public string BloqueadoMotivo { get; set; } = string.Empty;
        public bool Atacado { get; set; } = false;
        public DateTime? RenovarCadastro { get; set; } = null;
        public decimal RendaPessoal { get; set; } = 0.00m;
        public decimal RendaConjuge { get; set; } = 0.00m;
        public decimal RendaOutras { get; set; } = 0.00m;
        public string RefPessoal1 { get; set; } = string.Empty;
        public string RefPessoal1Tel { get; set; } = string.Empty;
        public string RefPessoal2 { get; set; } = string.Empty;
        public string RefPessoal2Tel { get; set; } = string.Empty;
        public string RefComercial1 { get; set; } = string.Empty;
        public string RefComercial1Tel { get; set; } = string.Empty;
        public string RefComercial2 { get; set; } = string.Empty;
        public string RefComercial2Tel { get; set; } = string.Empty;
        public string RefBancoNome { get; set; } = string.Empty;
        public string RefBancoAgencia { get; set; } = string.Empty;
        public string RefBancoConta { get; set; } = string.Empty;
        public string RefBancoTipo { get; set; } = string.Empty;
        public string RefBancoTempo { get; set; } = string.Empty;
        public string RefEmpresa { get; set; } = string.Empty;
        public string RefEmpresaTel { get; set; } = string.Empty;
        public string RefCargo { get; set; } = string.Empty;
        public string RefTempoServico { get; set; } = string.Empty;
        public string Uf { get; set; } = "MG";
        public string UfCob { get; set; } = string.Empty;
        public bool IsentoDoIcms { get; set; } = false;
        public string? InscricaoSuframa { get; set; } = null;
        public string Pais { get; set; } = "Brasil";
        public DateTime DataControl { get; set; } = DateTime.Now;
        public bool MalaDireta { get; set; } = false;
        public decimal LimiteDeCheques { get; set; } = 0.00m;
        public bool AddUpd { get; set; } = false;
        public string Celular2 { get; set; } = string.Empty;
        public string CodigoMunicipio  => IBGEManagement.GetCidadeByNome(Enum.Parse<EstadosEnum>(Uf == string.Empty ? "MG" : Uf), Cidade)?.CodMunicipio.ToString() ?? string.Empty;
        public string CodigoMunicipioCob { get; set; } = string.Empty;
        public string? IdEstrangeiro { get; set; } = null;
        public bool AvisoNfs { get; set; } = false;
    }
}
